# Generated by Django 5.0.6 on 2024-05-22 03:19

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, null=True)),
                ('last_name', models.CharField(blank=True, null=True)),
                ('middle_name', models.CharField(blank=True, null=True)),
                ('username', models.CharField(db_index=True, unique=True)),
                ('password', models.TextField()),
            ],
            bases=(models.Model, common.models.ABSModel),
        ),
    ]
