# Generated by Django 5.0.6 on 2024-05-22 03:19

import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('middle_name', models.CharField(blank=True, null=True)),
            ],
            bases=(models.Model, common.models.ABSModel),
        ),
        migrations.CreateModel(
            name='Janr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
            bases=(models.Model, common.models.ABSModel),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, verbose_name='Название фильма')),
                ('description', models.TextField()),
                ('avatar', models.ImageField(upload_to='media/avatars')),
                ('movie_file', models.FileField(upload_to='media/movies')),
                ('main_artists', models.TextField()),
                ('artists', models.TextField()),
                ('authors', models.ManyToManyField(to='cinematica.author')),
                ('janr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='cinematica.janr')),
            ],
            bases=(models.Model, common.models.ABSModel),
        ),
        migrations.CreateModel(
            name='ReviewToMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(blank=True, choices=[(1, 'ONE'), (2, 'TWO'), (3, 'THREE'), (4, 'FOUR'), (5, 'FIVE')], null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cinematica.movie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='account.user')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'unique_together': {('user_id', 'movie_id')},
            },
            bases=(models.Model, common.models.ABSModel),
        ),
    ]
